version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Pass
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Pass -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_SERVER=db
      - DB_PORT=1433
      - DB_NAME=HealthBeatDB
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Pass
      - SECRET_KEY=your-super-secret-key-change-in-production-min-32-chars
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  mssql_data: